### ISSUE TITLE
[US-01] List of books

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#1]
As a user I want to see a list of my books that I'm currently reading.

## Description
![us-01-list](https://user-images.githubusercontent.com/77329824/136403916-06613f2d-fd7e-439f-8299-bdaf421f1423.png)

## Acceptance criteria
- [x] List should contain all books that are currently or already read
- [x] Every book should be displayed with an image and some information about the book (title, author & reading since or finished & rating)
- [x] Every image should contain an alt-text

## Tasks
- [x] Create feature branch
- [x] Build book component for books
- [x] Build book list component for books
- [x] Add mock data for rendering and testing
- [x] Write tests for both components
- [x] Add book list to App
- [x] Add styled-components
