### ISSUE TITLE
[US-07] Local storage

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#10]
As a user, I want my newly saved books to still be there after reloading the app.

## Description
To fulfill these tasks, the data will be stored in the local storage.

## Acceptance criteria

- [x] After submitting a new book and reloading the app, the new book should still be displayed in the list of books currently read

## Tasks

- [x] Create a feature branch
- [x] Change component for adding a new book
- [x] Adjust tests if necessary
