### ISSUE TITLE
[US-09] Add new book with ISBN with preview

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#11]
As a user I want to see which book I searched via ISBN before adding it to the list of books.

## Description
![us-10-addbookISBN](https://user-images.githubusercontent.com/77329824/136528823-fd81c2ff-3c0b-4e6e-a8b6-7a02aa2853d1.png)

## Acceptance criteria

- [x]  If the ISBN is correct title, author and book cover will be automatically added
- [x] The user can independently complete the remaining data.
- [x] After submitting the new book the user should be redirected to currently reading page and see the new book on top of the booklist

## Tasks

- [x] Create feature branch
- [x] Change form component
- [x] Adjust tests
- [x] Add or change styled-components if necessary
