### ISSUE TITLE
[US-11] Details page (book)

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#13]
As a user I want to see more details about the book I am currently reading.

## Description
![us-13-return](https://user-images.githubusercontent.com/77329824/136555557-708f36c0-e817-4280-b028-262545133b79.png)

## Acceptance criteria

- [x] After selecting one card of the books currently read the user should de redirected to the details page of this specific book
- [x] The details page should display title, author, year, a description of the books content, the "reading since" date and on which page the user currently is
- [x] In the upper left corner there is a return button that takes the user back to the booklist page.
- [x] In the navigation the link to the page "currently reading" is no longer active
- [x] Clicking on the "currently reading" link in the navbar also takes the user to the corresponding booklist

## Tasks

- [x] Create feature branch
- [x] Create component
- [x] Add routing
- [x] Change booklist component
- [x] Write tests
- [x] Add styled-components

## Complexity
medium
