### ISSUE TITLE
[US-12] Change from currently reading to finished reading and back

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#15]
As a user I want to be able to change the status from my book to currently reading or finished reading.

## Description
![us-14-togglecurfin](https://user-images.githubusercontent.com/77329824/136559684-2738fe0a-f467-460d-8930-a57b08e05d9e.png)

![ideaCapstoneMareike](https://user-images.githubusercontent.com/77329824/138474741-6d505dd3-e7b7-4be2-a4c6-1ca7c2a9d681.png)

## Acceptance criteria

- [x] The user should be able to activate "Finished reading" in the details page
- [x] When finished is true , the content of the Details page changes to show the status "finished reading" and the date on which the book was finished.
- [x] User has the possibility to change back to the status "currently reading"
- [x] If user wants to return to the status "currently reading" the data to "reading since" and "currently on page" will be loaded and the status "finished reading" won't be displayed anymore
- [x] The library shows the finished book on top of the list
- [x] User has also the possibility to add finished status when he adds a new book to the list

## Tasks

- [x] Create feature branch
- [x] Change details page component
- [x] Change AddBookForm
- [x] Adjust tests
- [x] Add styled-components
