### ISSUE TITLE
[US-02] Filter list of books

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#2]
As a user I want to see a list of my books that I already read.

## Description
![us-02-filter](https://user-images.githubusercontent.com/77329824/136406237-60915527-7223-454f-811a-e7f449cbeeb9.png)
![us-02-filter2](https://user-images.githubusercontent.com/77329824/136406242-46847bd9-9d65-45a4-a658-a1943763eeef.png)

## Acceptance Criteria

- [x] User should be able to filter the list of his books by read and unread books with the help of two buttons
- [x] If the "currently reading" button is clicked, only the books that are currently being read should be displayed
- [x] If the "finished reading" button is clicked, only the books that have already been read should be displayed
- [x] User should be able to see which button is currently active through a title underneath the buttons

## Tasks

- [x] Create feature branch
- [x] Adjust booklist component by adding two buttons
- [ ] Add new tests and adjust old test for both components if necessary
- [x] Add book list to App
- [ ] Adjust and add styled-components

## Complexity
low
