### ISSUE TITLE
[US-13] Add icons to Navigation

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#27]
As a user I want to have icons instead of text in the navbar.

## Description

<img width="367" alt="Bildschirmfoto 2021-10-30 um 23 06 10" src="https://user-images.githubusercontent.com/77329824/139558401-f8212d5d-a7aa-428c-abe1-95afbf7d7ff9.png">

## Acceptance Criteria

- [x] Every NavLink should have its own icon according to the image above
- [x] If one NavLink is active the other should be inactive
- [x] The active status of a NavLink should be visible through color change

## Tasks

- [x] Create feature branch
- [x] Add icon svgs
- [x] Change styling of NavLinks
- [x] Adjust tests and component if necessary

## Complexity

low
