### ISSUE TITLE
[US-14] Edit book details page

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#28]
As user I want to have the opportunity to delete a book from my book list and to edit on which page I am on my currently read book to see on which page I really am.

## Description

![localhost_3000_book_KwqFgWf6VzISznnKgspWx(iPhone 6_7_8)](https://user-images.githubusercontent.com/77329824/139592007-111bbbdd-7016-4f3f-84c6-2e6fa1cb5a18.png)
![localhost_3000_book_KwqFgWf6VzISznnKgspWx(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/77329824/139592010-be91fefe-cf2b-443f-87b2-1c6f219e02e1.png)

## Acceptance Criteria

- [x] Drop Down Menu has another option "Delete book"
- [x] When the user clicks on this option the book will be removed and the user returns to his book list
- [x] The book is gone and can't be found in the list anymore
- [x] The user can find the option "Edit on page" in the drop down menu
- [x] By clicking this option the user has the option to enter the new page he is currently on
- [x] The user can also cancel this update
- [x] After clicking "update" the user can see his update under "Currently on page"
- [x] It is not possible to choose a page number that is higher than the pages length of the book he is reading

## Tasks

- [x] Create feature branch
- [x] Update Drop Down Menu component
- [x] Adjust tests and styled components if necessary
- [x] Create new component for page update
- [x] Add tests for new component
- [x] Update tests of other components if necessary
- [x] Add styled-components

## Complexity
medium
