### ISSUE TITLE
[US-03] Navigation

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#3]
As a user I want to navigate between the list of books currently read and the list of books already read.

## Description
![us-03-nav02](https://user-images.githubusercontent.com/77329824/136410712-18c07ecc-7a97-4554-842c-b14e63d37fa8.png)
![us-03-nav01](https://user-images.githubusercontent.com/77329824/136410640-11cb5087-676c-4044-8a63-b41aeb94a4ba.png)

## Acceptance criteria

- [x] Navigation should be displayed at the bottom of the viewport
- [x] Navigation should always be visible for user
- [x] The navigation should show which list the user is currently looking at

## Tasks

- [x] Create feature branch
- [x] Build navigation component
- [x] Add routing to App
- [x] Remove buttons from the top of the list
- [x] Write test for component
- [x] Add styled-components

## Complexity
low
