### ISSUE TITLE
[Task] Refactoring

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#31]
## Tasks:
- [x] create feature branch
- [x] sort App imports
- [x] move successMessage from App: useEffect to AddBook with state var & function for successMessage for AddBookForm
- [x] extract formatData function in utils
- [x] delete console.logs
- [x] extract code that doesn't belong to get request and put it in handleSubmit function
- [x] extract getBook in services
- [x] move FileReader and bookcover from App to AddBookForm
- [x] change history
- [x] Rename StartAddBook in SearchViaISBN (adjust components, tests, stories etc.)
