### ISSUE TITLE
[Task] Refactoring (second round)

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#37]
## Tasks
- [x] Create feature branch
- [x] Add CSS variables
- [x] Adjust styled-components
- [x] Remove unnecessary code
- [x] Adjust GlobalStyles
- [x] Adjust date
- [x] Adjust bookcover preview
- [x] Adjust tests if necessary
- [x] Add scroll to top
- [x] Remove line clamping
- [x] Add update message
