### ISSUE TITLE
[US-06] Add new book to list of books currently read

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#6]
As a user I want to navigate to a page where I can add a new book to my list of books currently read.

## Description
![addbooktonav](https://user-images.githubusercontent.com/77329824/136390048-c4690dd5-a8f7-4acc-a3d5-b6aac2857259.png)

## Acceptance criteria
- [x] User can enter information about the book (title and author) and reading status (since when the book is read and on which page the user is currently) and also upload an image
- [x] Title and author are required for adding a new book
- [x] If there is no image a placeholder image will be added
- [x] After completing the form the user should be redirected to list of books currently read and see the book on top of the booklist
- [x] Navigation should show three navlinks("Currently reading", "Library" & "Add new book"
- [x] The user should be directed to the page where he can add a new book to the list of books currently read by clicking on the navlink "Add new book"

## Tasks

- [x] Create feature branch 
- [x] Create add book component
- [x] Change component for list of books currently read
- [x] Write tests for new component
- [x] Add component to App
- [x] Change navigation component
- [x] Change test for components if necessary
- [x] Add route for component "AddBook" in App
- [x] Add and adjust styled components
