### ISSUE TITLE
[US-08] Add new book to list of books currently read via ISBN

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#7]
As a user I want to add a new book to my list of books currently read by using the ISBN because it is more convenient.

## Description
![us-08-ISBN01](https://user-images.githubusercontent.com/77329824/136525009-5b6a52f5-061e-46c0-b9fa-1cda3570699b.png)
![us-08-ISBN03](https://user-images.githubusercontent.com/77329824/136526696-658fdeee-90ae-4f84-8e04-0519fa5fa9f1.png)
![us-08-ISBN02](https://user-images.githubusercontent.com/77329824/136525037-bebe61c8-8498-4880-92fb-5a62a142858d.png)

## Acceptance criteria

- [x] User can add a new book via ISBN
- [x] If the ISBN is available, the book will be automatically added to the book list
- [x] If the ISBN is wrong, the user gets an error message
- [x] If user wants to add the new book manually he can go to the already implemented form for adding a new book by clicking on the "click here" button
- [x] After adding a new book the user should be redirected to currently reading page
- [x] The newly added book should be displayed on top of the booklist

## Tasks

- [x] Create feature branch 
- [x] Create new component
- [x] Change text in form component for adding a new book
- [x] Add component to App and add from component to new component and remove ist from app component
- [x] Add redirection to form component in new component
- [x] Add tests for new component
- [x] Add styled-components

## Complexity
medium
