### ISSUE TITLE
[US-04] Add start screen

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#8]
As a user I want to start my app and enter my name.

## Description
![us-04-start](https://user-images.githubusercontent.com/77329824/136413863-c9e0dea3-8856-4e61-9fd7-93b1e1cea5fa.png)

## Acceptance criteria

- [x] User should see the logo and name of the app and a field where the person should insert their name and a start button
- [x] After entering a name and click on the button user should be redirected to the list of books currently read
- [x] It is not possible to go beyond this page if name is not inserted

## Tasks

- [x] Create feature branch
- [x] Create start screen component
- [x] Write tests and stories components
- [x] Add styled components
