### ISSUE TITLE
[US-05] Add personalization

### ISSUE THREAD

**Issue by mbosselmann** [mbosselmann/capstone-project#9]
As a user, I want to see my name in the app to make a personal connection with my app.

## Description
![us-05-personal](https://user-images.githubusercontent.com/77329824/136432697-f7a09162-b370-4933-9130-dad681aeb17d.png)

## Acceptance criteria

- [x] After redirecting from the start screen to the book list which shows  the books currently read the user should see the name above the book list that he/she previously entered in the input field. 

## Tasks

- [x] Create feature branch
- [x] Change text in booklist component which will be displayed above of the booklist
- [x] Add described username function
- [x] Add new test to component
- [x] Change styled-components
